# .github/workflows/check-semver.yml

name: Check Semantic Version
 
on:

  push:

    branches:

      - master
 
jobs:

  check-version:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout code

        uses: actions/checkout@v4
 
      - name: Set up Python

        uses: actions/setup-python@v5

        with:

          python-version: '3.x'
 
      - name: Install python-semantic-release

        run: |

          python -m pip install --upgrade pip

          pip install python-semantic-release
 
      - name: Dry run semantic release

        run: |

          python-semantic-release version --noop --debug

 